---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/monolith_db
    username: root
    password: root
  redis:
    host: redis
    port: 6379
  kafka:
    bootstrap-servers: kafka:9092

