services:
  mysql:
    image: mysql:8.4
    container_name: msa-ecommerce-mysql
    restart: no
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: db_flyway
      MYSQL_USER: app_rw
      MYSQL_PASSWORD: 1q2w3e4r!
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=200
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$${MYSQL_ROOT_PASSWORD}" ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s

  redis:
    image: redis:8.0.3
    container_name: msa-ecommerce-redis
    restart: no
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: 1q2w3e4r
    command: [ "sh","-lc","exec redis-server --appendonly yes --requirepass \"$$REDIS_PASSWORD\"" ]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" --raw PING" ]
      timeout: 5s
      retries: 5
      interval: 10s
      start_period: 10s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: msa-ecommerce-zookeeper
    restart: no
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc localhost 2181 | grep imok" ]
      timeout: 5s
      retries: 5
      interval: 10s
      start_period: 10s

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: msa-ecommerce-kafka
    restart: no
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list" ]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 30s
