server:
  port: 8081

spring:
  application:
    name: order-orchestrator

  datasource:
    url: jdbc:mysql://localhost:3306/db_order
    username: app_rw
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
    group: true
    schemas: db_order
    default-schema: db_order

logging:
  level:
    com.msa.commerce: DEBUG
