name: "🔧 Refactoring"
description: "코드 구조 개선 및 리팩토링"
labels: [ "refactoring", "improvement" ]
body:
  - type: textarea
    attributes:
      label: 📄 리팩토링 대상
      description: 리팩토링하고자 하는 코드나 모듈에 대한 설명을 작성해 주세요.
      placeholder: |
        예시:
        - 대상 파일/모듈: src/main/java/com/example/service/UserService.java
        - 현재 문제점: 메서드가 너무 길고 책임이 분산되어 있음
        - 개선하고자 하는 부분: 단일 책임 원칙 적용, 메서드 분리
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 🎯 리팩토링 유형
      description: 주요 리팩토링 유형을 선택해 주세요.
      options:
        - "코드 구조 개선 (메서드/클래스 분리)"
        - "성능 최적화"
        - "가독성 향상"
        - "중복 코드 제거 (DRY 원칙)"
        - "디자인 패턴 적용"
        - "테스트 코드 개선"
        - "의존성 정리"
        - "네이밍 개선"
        - "기타"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: ⚡ 우선순위
      description: 리팩토링의 긴급성과 중요성을 선택해 주세요.
      options:
        - "🔴 High - 즉시 처리 필요 (성능 이슈, 보안 취약점 등)"
        - "🟡 Medium - 다음 스프린트에서 처리"
        - "🟢 Low - 시간이 날 때 처리"
    validations:
      required: true

  - type: textarea
    attributes:
      label: 💡 기대 효과
      description: 리팩토링 후 기대되는 개선 사항을 작성해 주세요.
      placeholder: |
        예시:
        - 코드 가독성 향상으로 유지보수성 증대
        - 성능 20% 향상 예상
        - 테스트 커버리지 증가
        - 코드 복잡도 감소
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 리팩토링 작업을 체크박스 형태로 세분화해서 작성해주세요.
      placeholder: |
        - [ ] 현재 코드 분석 및 문제점 파악
        - [ ] 리팩토링 계획 수립
        - [ ] 단위 테스트 작성/보완
        - [ ] 코드 리팩토링 실행
        - [ ] 통합 테스트 실행
        - [ ] 성능 테스트 (필요시)
        - [ ] 코드 리뷰 요청
        - [ ] 문서 업데이트
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 📋 사전 체크리스트
      description: 리팩토링 전 확인해야 할 사항들
      options:
        - label: "기존 기능에 대한 테스트 코드가 존재하는가?"
        - label: "리팩토링 범위가 명확하게 정의되었는가?"
        - label: "관련 팀원들과 논의가 완료되었는가?"
        - label: "백업 계획이 수립되었는가?"

  - type: textarea
    attributes:
      label: 🙋🏻 참고 자료
      description: 관련 문서, 레퍼런스, 이슈 등이 있다면 작성해 주세요.
      placeholder: |
        - 관련 이슈: #123
        - 참고 문서: https://...
        - 디자인 패턴 가이드: https://...
