---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/payment_db
    username: root
    password: root
  kafka:
    bootstrap-servers: kafka:9092

